; Test.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 52.0
.source Test.java
.class public Test
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 2
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static main([Ljava/lang/String;)V
  .limit stack 2
  .limit locals 3
  .line 6
  0: iconst_0
  1: istore_2
Label2:
  2: iload_2
  3: bipush 10
  5: if_icmple Label22
  .line 7
  8: getstatic java/lang/System/out Ljava/io/PrintStream;
  11: ldc "Hello"
  13: invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V
  .line 6
  16: iinc 2 1
  19: goto Label2
Label22:
  .line 9
  22: return
  ; append_frame (frameNumber = 0)
  ; frame_type = 253, offset_delta = 2
  ; frame bytes: 253 0 2 0 1 
  .stack 
    offset 2
    locals Top
    locals Integer
    .end stack
  ; chop_frame (frameNumber = 1)
  ; frame_type = 249, offset_delta = 19
  ; frame bytes: 249 0 19 
  .stack 
    offset 22
    .end stack
.end method


