; Test.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 52.0
.source Test.java
.class public Test
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 2
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static main([Ljava/lang/String;)V
  .limit stack 1
  .limit locals 6
  .line 5
  0: iconst_1
  1: istore_1
  .line 6
  2: iconst_1
  3: istore_2
  .line 7
  4: iconst_1
  5: istore_3
  .line 8
  6: iconst_1
  7: istore 4
  .line 9
  9: iconst_1
  10: istore 5
  .line 11
  12: iinc 3 1
  .line 13
  15: return
.end method


